### ISSUE TITLE
ValueError: insecure string pickle

### ISSUE THREAD

**Issue by jobim3d** [ironfist2/body_poses#1]
Hi, with Python 2.7 under windows I get this error:

```
Traceback (most recent call last):
  File "detect_poses.py", line 9, in <module>
    train_model = pickle.load(pickle_file)['log']
  File "c:\Python27\lib\pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "c:\Python27\lib\pickle.py", line 864, in load
    dispatch[key](self)
  File "c:\Python27\lib\pickle.py", line 972, in load_string
    raise ValueError, "insecure string pickle"
ValueError: insecure string pickle
```

Can you help?
Thnak you.

**Comment by ironfist2** [comment]
Sorry for the late reply. Apparently it was because of an unclosed file 'train_model.pickle' in the code in trainer.py. Now It has been resolved.
